In [1]:
from easyAI  import TwoPlayersGame, Human_Player, AI_Player, Negamax
import numpy as np

In [2]:
class TresEnRaya(TwoPlayersGame):
    def __init__(self, numeroJugadores):
        self.tablero = np.zeros((3,3), dtype = int)
        self.nplayer = 1
        self.mapa = {}
        cont = 1
        for i in range(len(self.tablero)):
            for j in range(len(self.tablero)):
                self.mapa[cont] = (i,j)
                cont+=1
        self.players = numeroJugadores
    def possible_moves(self):
        moves = []
        cont = 1
        for i in range(len(self.tablero)):
            for j in range(len(self.tablero)):
                if self.tablero[i][j] == 0:
                    moves.append(cont);
                cont +=1
        return moves
    def make_move(self, casillero):
        pos = self.mapa[casillero]
        self.tablero[pos[0]][pos[1]] = self.nplayer
    def unmake_move(self, casillero):
        pos = self.mapa[casillero]
        self.tablero[pos[0]][pos[1]] = 0
    def lose(self):
        for i in range (len(self.tablero)):
            if np.all(self.tablero[i,:]==self.nopponent, axis = 0) or np.all(self.tablero[:,i] == self.nopponent, axis = 0):
                return True
            if self.tablero[0][0] == self.nopponent and self.tablero[1][1] == self.nopponent and self.tablero[2][2] == self.nopponent:
                return True
            if self.tablero[2][0] == self.nopponent and self.tablero[1][1] == self.nopponent and self.tablero[0][2] == self.nopponent: 
                return True
        return False
    def show(self):
        print(self.tablero)
    def scoring(self):
        return -100 if self.lose() else 0
    def is_over(self):
        return (self.possible_moves() == [] or self.lose())

    

In [ ]:
if __name__=="__main__":
    ai_algo = Negamax(6)
    tresenraya = TresEnRaya([Human_Player(), AI_Player(ai_algo)])
    tresenraya.play()

[[0 0 0]
 [0 0 0]
 [0 0 0]]
